name: ubuntu-build

on: pull_request

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
     - uses: actions/checkout@v2
     - name: Setup Swift Action
       uses: tgymnich/setup-swift@v1.0.4
       with:
         version: '5.3'
     - name: Build
       run: swift build -v
     - name: Test
       run: swift test -v
