name: mac-build

on: pull_request

jobs:
  macOsTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Unit Test
      run: swift test -v 
  